spring.application.name=Job Applications Tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/job_applications
spring.datasource.username=tracker
spring.datasource.password=JOBtracker
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
